/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_gpio.h"
#include "../HAL/LCD/LCD.h"
#include "../HAL/LCD/LCD_CFG.h"
#include "../HAL/KEYPAD/KEYPAD.h"
#include "../HAL/KEYPAD/KEYPAD_CFG.h"

/* ========== Prototypes ========= */
void clock_init(void);
static void delay_ms(uint32_t delay);

/* =========== Main Program ========== */
int main(void)
{
	// Initializing the clock
	clock_init();

	// Initializing the LCD
	HAL_LCD_INIT();

	// Initializing the 7-segment

	HAL_LCD_WRITE_STRING("Hey Maleka! I Am Basem");
	delay_ms(1000);
	HAL_LCD_CLEAR_SCREEN();

	// Variable to check pressed key of Keypad
	HAL_LCD_WRITE_STRING("My Number is :");
	delay_ms(1000);
	HAL_LCD_CLEAR_SCREEN();
	uint8_t pressed_key;



	// Array to store Numbers from 1 >>> 9 to be displayed on LCD
	uint8_t LCD_Numbers[] = {'0', '1', '0', '1', '1', '1', '6', '6', '6', '7', '7'};

	// Loop to display the same number to LCD and 7-SEGMENT
	for (uint8_t i = 0; i < 11; i++)
	{
		// Display current number on the 7 segment
		// We shifted by 9 as we used the First 9 Ports for Keypad and started connecting 7 segment from PB10

		// Display current number on the LCD
		HAL_LCD_WRITE_CHAR(LCD_Numbers[i]);
		// Delay to be able to see the change in numbers
		delay_ms(100);  // delay
	}
		delay_ms(1000);  // delay

	// Clear screen after displaying Numbers
	HAL_LCD_CLEAR_SCREEN();

	// Initializing the Keypad
	HAL_LCD_WRITE_STRING("Keypad is ready!");
	delay_ms(1000);
	HAL_KEYPAD_INIT();

	HAL_LCD_CLEAR_SCREEN();

	while(1)
	{
		pressed_key = HAL_KEYPAD_GET_KEY();

		if(pressed_key == 0)
		{
			continue;
		}
		else {
			if(pressed_key == 'C') HAL_LCD_CLEAR_SCREEN();
			else HAL_LCD_WRITE_CHAR(pressed_key);
		}

	}
}

/* ======== clock init definition ======= */
void clock_init(void)
{
	// Enable clock GPIOA
	RCC_GPIOA_CLK_EN();

	// Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

static void delay_ms(uint32_t delay)
{
	uint32_t i, j;
	for (i = 0; i < delay; i++)
	{
		for (j = 0; j < 255; j++);
	}
}
