/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800

#define RCC_APB2ENR *(volatile uint32_t *) (RCC_BASE + 0x18)
#define GPIOA_CRH   *(volatile uint32_t *) (PORTA_BASE + 0x04)
#define GPIOA_ODR   *(volatile uint32_t *) (PORTA_BASE + 0x0C) // Corrected address

int main(void)
{
    // Enable clock for GPIOA
	RCC_APB2ENR |= 1 << 2;

    // Configure PA11 as output (general purpose output push-pull, max speed 2 MHz)
	GPIOA_CRH &= 0xFFFF0FFF; // Clear bits 15-12 for PA11
	GPIOA_CRH |= 0x00002000; // Set mode to 0010: Output mode, max speed 2 MHz

    /* Loop forever */
	while (1)
	{
		GPIOA_ODR |= 1 << 11;  // Set PA11
		for (int i = 0; i < 100000; i++); // Delay
		GPIOA_ODR &= ~(1 << 11); // Clear PA11
		for (int i = 0; i < 100000; i++); // Delay
	}
}
